### PR TITLE
3.2.1

### PR DESCRIPTION
**Pull request by lpiedade**
*Issue #6 *

*Description of changes:*
 - Elasticsearch version update to 7.4
 - NodeJS update to 12.x
 - Update README.md

### CODE REVIEW

**Comment by mobri2a** [comment]
Thanks for the suggestion. Elasticsearch will be upgrade in a future release. Updating the solution to 7.4 without an upgrade path would make it difficult for current customers of the solution to upgrade, so documenting the upgrade is an important part.

**Comment by lpiedade** [comment]
Hi @mobri2a, I agree with you. If somebody would like to update the Elasticsearch version could just run "update stack" action using this CloudFormation template, but it would be great to find this information on the documentation.

**Comment by maykays** [comment]
Please up-vote if you want this feature. Do not submit a new feature request.

**Comment by maykays** [comment]
Related to/
Duplicate of #20

**Pull request closed without merging**
